package cn.iocoder.stmc.module.erp.dal.dataobject.voucher;

import cn.iocoder.stmc.framework.mybatis.core.dataobject.BaseDO;
import com.baomidou.mybatisplus.annotation.FieldStrategy;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ERP 票据凭证 DO
 *
 * @author stmc
 */
@TableName("erp_voucher")
@KeySequence("erp_voucher_seq")
@Data
@EqualsAndHashCode(callSuper = true)
public class VoucherDO extends BaseDO {

    @TableId
    private Long id;

    /** 关联订单ID（必填） */
    private Long orderId;

    /** 发票类型：1=增值税专用发票 2=普通发票 3=定额发票 4=其他发票；系统预制票可为空 */
    @TableField(updateStrategy = FieldStrategy.ALWAYS)
    private Integer voucherType;

    /** 方向：0=进项（采购） 1=销项（销售） */
    private Integer direction;

    /** 对方单位（进项=采购方，销项=客户） */
    private String counterparty;

    /** 发票代码 */
    private String invoiceCode;

    /** 价税合计 */
    private BigDecimal amount;

    /** 税额 */
    private BigDecimal taxAmount;

    /** 来源类型：1=采购应付计划预制进项票 2=收款计划预制销项票 */
    private Integer sourceType;

    /** 来源计划ID */
    private Long sourcePlanId;

    /** 是否系统自动预制：0=否 1=是 */
    private Boolean autoGenerated;

    /** 开票日期 */
    private LocalDate invoiceDate;

    /** 文件URL */
    private String fileUrl;

    /** 文件名 */
    private String fileName;

    /** 备注 */
    private String remark;

    /** 核销状态：0=未核销 1=已核销 2=不匹配 */
    private Integer reconcileStatus;

    /** 核销备注 */
    private String reconcileRemark;

}
