package cn.iocoder.stmc.module.erp.dal.mysql.voucher;

import cn.iocoder.stmc.framework.common.pojo.PageResult;
import cn.iocoder.stmc.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.stmc.framework.mybatis.core.query.LambdaQueryWrapperX;
import cn.iocoder.stmc.module.erp.controller.admin.voucher.vo.VoucherPageReqVO;
import cn.iocoder.stmc.module.erp.dal.dataobject.voucher.VoucherDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * ERP 票据凭证 Mapper
 *
 * @author stmc
 */
@Mapper
public interface VoucherMapper extends BaseMapperX<VoucherDO> {

    default PageResult<VoucherDO> selectPage(VoucherPageReqVO reqVO) {
        return selectPage(reqVO, new LambdaQueryWrapperX<VoucherDO>()
                .eqIfPresent(VoucherDO::getVoucherType, reqVO.getVoucherType())
                .eqIfPresent(VoucherDO::getDirection, reqVO.getDirection())
                .eqIfPresent(VoucherDO::getReconcileStatus, reqVO.getReconcileStatus())
                .eqIfPresent(VoucherDO::getOrderId, reqVO.getOrderId())
                .likeIfPresent(VoucherDO::getInvoiceCode, reqVO.getInvoiceCode())
                .orderByDesc(VoucherDO::getId));
    }

    default List<VoucherDO> selectListByOrderId(Long orderId) {
        return selectList(new LambdaQueryWrapperX<VoucherDO>()
                .eq(VoucherDO::getOrderId, orderId)
                .orderByDesc(VoucherDO::getId));
    }

    default List<VoucherDO> selectListByAutoGeneratedSource(Integer sourceType, Long sourcePlanId) {
        return selectList(new LambdaQueryWrapperX<VoucherDO>()
                .eq(VoucherDO::getAutoGenerated, true)
                .eq(VoucherDO::getSourceType, sourceType)
                .eq(VoucherDO::getSourcePlanId, sourcePlanId)
                .orderByAsc(VoucherDO::getId));
    }

    default List<VoucherDO> selectListByAutoGeneratedPlanId(Long sourcePlanId) {
        return selectList(new LambdaQueryWrapperX<VoucherDO>()
                .eq(VoucherDO::getAutoGenerated, true)
                .eq(VoucherDO::getSourcePlanId, sourcePlanId)
                .orderByAsc(VoucherDO::getId));
    }

}
