package cn.iocoder.stmc.module.erp.controller.admin.voucher.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Schema(description = "管理后台 - ERP 票据凭证 Response VO")
@Data
public class VoucherRespVO {

    @Schema(description = "编号", requiredMode = Schema.RequiredMode.REQUIRED, example = "1")
    private Long id;

    @Schema(description = "关联订单ID", example = "1")
    private Long orderId;

    @Schema(description = "订单号", example = "SO20240101001")
    private String orderNo;

    @Schema(description = "发票类型：1=增值税专用发票 2=普通发票 3=定额发票 4=其他发票；系统预制票可为空", example = "1")
    private Integer voucherType;

    @Schema(description = "方向：0=进项 1=销项", example = "0")
    private Integer direction;

    @Schema(description = "对方单位（进项=采购方，销项=客户）", example = "供应商A")
    private String counterparty;

    @Schema(description = "发票代码", example = "012345678901")
    private String invoiceCode;

    @Schema(description = "价税合计", example = "10000.00")
    private BigDecimal amount;

    @Schema(description = "来源类型：1=采购应付计划预制进项票 2=收款计划预制销项票", example = "1")
    private Integer sourceType;

    @Schema(description = "来源计划ID", example = "1")
    private Long sourcePlanId;

    @Schema(description = "是否系统自动预制", example = "true")
    private Boolean autoGenerated;

    @Schema(description = "开票日期", example = "2024-01-01")
    private LocalDate invoiceDate;

    @Schema(description = "文件URL", example = "https://xxx.com/file.pdf")
    private String fileUrl;

    @Schema(description = "文件名", example = "发票.pdf")
    private String fileName;

    @Schema(description = "备注", example = "3月份采购发票")
    private String remark;

    @Schema(description = "核销状态：0=未核销 1=已核销 2=不匹配", example = "0")
    private Integer reconcileStatus;

    @Schema(description = "核销备注", example = "金额不匹配")
    private String reconcileRemark;

    @Schema(description = "创建时间")
    private LocalDateTime createTime;

}
