package cn.iocoder.stmc.module.erp.service.voucher;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.exceptions.ExceptionUtil;
import cn.iocoder.stmc.framework.common.pojo.PageResult;
import cn.iocoder.stmc.framework.common.util.object.BeanUtils;
import cn.iocoder.stmc.module.erp.controller.admin.voucher.vo.VoucherPageReqVO;
import cn.iocoder.stmc.module.erp.controller.admin.voucher.vo.VoucherSaveReqVO;
import cn.iocoder.stmc.module.erp.dal.dataobject.customer.CustomerDO;
import cn.iocoder.stmc.module.erp.dal.dataobject.paymentplan.PaymentPlanDO;
import cn.iocoder.stmc.module.erp.dal.dataobject.supplier.SupplierDO;
import cn.iocoder.stmc.module.erp.dal.dataobject.voucher.VoucherDO;
import cn.iocoder.stmc.module.erp.dal.mysql.voucher.VoucherMapper;
import cn.iocoder.stmc.module.erp.service.customer.CustomerService;
import cn.iocoder.stmc.module.erp.service.supplier.SupplierService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

import javax.annotation.Resource;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

import static cn.iocoder.stmc.framework.common.exception.util.ServiceExceptionUtil.exception;
import static cn.iocoder.stmc.module.erp.enums.ErrorCodeConstants.VOUCHER_NOT_EXISTS;

/**
 * ERP 票据凭证 Service 实现类
 *
 * @author stmc
 */
@Slf4j
@Service
@Validated
public class VoucherServiceImpl implements VoucherService {

    private static final Integer PLAN_TYPE_PAYABLE = 0;
    private static final Integer PLAN_TYPE_RECEIVABLE = 1;
    private static final Integer SOURCE_TYPE_PAYABLE_PLAN = 1;
    private static final Integer SOURCE_TYPE_RECEIVABLE_PLAN = 2;
    private static final Integer DIRECTION_INPUT = 0;
    private static final Integer DIRECTION_OUTPUT = 1;
    private static final Integer RECONCILE_STATUS_PENDING = 0;
    private static final String EMPTY_INVOICE_CODE = "";
    private static final String AUTO_VOUCHER_UNIQUE_INDEX = "uk_source_plan_autogen_active";
    private static final String OPERATION_CREATE = "create";
    private static final String OPERATION_SYNC = "sync";
    private static final String OPERATION_DELETE = "delete";

    @Resource
    private VoucherMapper voucherMapper;
    @Resource
    private SupplierService supplierService;
    @Resource
    private CustomerService customerService;

    @Override
    public Long createVoucher(VoucherSaveReqVO reqVO) {
        VoucherDO voucher = BeanUtils.toBean(reqVO, VoucherDO.class);
        if (voucher.getReconcileStatus() == null) {
            voucher.setReconcileStatus(0); // 默认未核销
        }
        voucherMapper.insert(voucher);
        return voucher.getId();
    }

    @Override
    public void updateVoucher(VoucherSaveReqVO reqVO) {
        validateVoucherExists(reqVO.getId());
        VoucherDO updateObj = BeanUtils.toBean(reqVO, VoucherDO.class);
        voucherMapper.updateById(updateObj);
    }

    @Override
    public void deleteVoucher(Long id) {
        validateVoucherExists(id);
        voucherMapper.deleteById(id);
    }

    @Override
    public VoucherDO getVoucher(Long id) {
        return voucherMapper.selectById(id);
    }

    @Override
    public PageResult<VoucherDO> getVoucherPage(VoucherPageReqVO pageReqVO) {
        return voucherMapper.selectPage(pageReqVO);
    }

    @Override
    public List<VoucherDO> getVoucherListByOrderId(Long orderId) {
        return voucherMapper.selectListByOrderId(orderId);
    }

    @Override
    public void reconcileVoucher(Long id, Integer reconcileStatus, String reconcileRemark) {
        VoucherDO voucher = validateVoucherExists(id);
        VoucherDO updateObj = new VoucherDO();
        updateObj.setId(id);
        updateObj.setReconcileStatus(reconcileStatus);
        updateObj.setReconcileRemark(reconcileRemark);
        voucherMapper.updateById(updateObj);
    }

    @Override
    public void createAutoVoucherFromPlan(PaymentPlanDO plan) {
        final String methodName = "createAutoVoucherFromPlan";
        if (!isValidPlan(plan, methodName)) {
            return;
        }

        AutoVoucherRule rule = resolveAutoVoucherRule(plan, methodName);
        if (rule == null) {
            return;
        }

        try {
            List<VoucherDO> existingVouchers = voucherMapper.selectListByAutoGeneratedSource(rule.getSourceType(), plan.getId());
            if (CollUtil.isNotEmpty(existingVouchers)) {
                log.info("[{}] 预制票已存在，跳过创建，planId={}, sourceType={}, count={}",
                        methodName, plan.getId(), rule.getSourceType(), existingVouchers.size());
                return;
            }

            List<VoucherDO> legacyVouchers = voucherMapper.selectListByAutoGeneratedPlanId(plan.getId());
            if (CollUtil.isNotEmpty(legacyVouchers)) {
                log.info("[{}] 发现同计划旧来源预制票，按已存在处理并跳过创建，planId={}, sourceType={}, count={}",
                        methodName, plan.getId(), rule.getSourceType(), legacyVouchers.size());
                return;
            }

            VoucherDO voucher = buildAutoVoucher(plan, rule);
            voucherMapper.insert(voucher);
        } catch (DuplicateKeyException e) {
            if (isAutoVoucherDuplicateConflict(e)) {
                log.info("[{}] 并发创建命中目标唯一约束，按已存在处理并跳过，planId={}, sourceType={}, message={}",
                        methodName, plan.getId(), rule.getSourceType(), ExceptionUtil.getRootCauseMessage(e));
                return;
            }
            logExpectedAutoVoucherFailure(methodName, OPERATION_CREATE, plan, rule, e);
        } catch (DataAccessException e) {
            logExpectedAutoVoucherFailure(methodName, OPERATION_CREATE, plan, rule, e);
        }
    }

    @Override
    public void syncAutoVouchersFromPlan(PaymentPlanDO plan) {
        final String methodName = "syncAutoVouchersFromPlan";
        if (!isValidPlan(plan, methodName)) {
            return;
        }

        AutoVoucherRule rule = resolveAutoVoucherRule(plan, methodName);
        if (rule == null) {
            return;
        }

        try {
            List<VoucherDO> vouchers = voucherMapper.selectListByAutoGeneratedSource(rule.getSourceType(), plan.getId());
            if (CollUtil.isEmpty(vouchers)) {
                vouchers = voucherMapper.selectListByAutoGeneratedPlanId(plan.getId());
            }
            if (CollUtil.isEmpty(vouchers)) {
                return;
            }

            String counterparty = resolveCounterparty(plan);
            int syncCount = 0;
            int skippedCount = 0;
            for (VoucherDO voucher : vouchers) {
                if (hasInvoiceCode(voucher)) {
                    skippedCount++;
                    continue;
                }
                VoucherDO updateObj = new VoucherDO();
                updateObj.setId(voucher.getId());
                updateObj.setAmount(plan.getPlanAmount());
                updateObj.setCounterparty(counterparty);
                updateObj.setDirection(rule.getDirection());
                updateObj.setSourceType(rule.getSourceType());
                voucherMapper.updateById(updateObj);
                syncCount++;
            }

            if (syncCount > 0 || skippedCount > 0) {
                log.info("[{}] 同步预制票完成，planId={}, sourceType={}, syncedCount={}, skippedLockedCount={}",
                        methodName, plan.getId(), rule.getSourceType(), syncCount, skippedCount);
            }
        } catch (DataAccessException e) {
            logExpectedAutoVoucherFailure(methodName, OPERATION_SYNC, plan, rule, e);
        }
    }

    @Override
    public void deleteAutoVouchersByPlan(PaymentPlanDO plan) {
        final String methodName = "deleteAutoVouchersByPlan";
        if (!isValidPlan(plan, methodName)) {
            return;
        }

        AutoVoucherRule rule = resolveAutoVoucherRule(plan, methodName);
        if (rule == null) {
            return;
        }

        try {
            List<VoucherDO> vouchers = voucherMapper.selectListByAutoGeneratedSource(rule.getSourceType(), plan.getId());
            if (CollUtil.isEmpty(vouchers)) {
                vouchers = voucherMapper.selectListByAutoGeneratedPlanId(plan.getId());
            }
            if (CollUtil.isEmpty(vouchers)) {
                return;
            }

            List<Long> ids = vouchers.stream()
                    .map(VoucherDO::getId)
                    .filter(id -> id != null)
                    .collect(Collectors.toList());
            if (CollUtil.isEmpty(ids)) {
                return;
            }

            int deletedCount = voucherMapper.deleteBatchIds(ids);
            log.info("[{}] 删除预制票完成，planId={}, sourceType={}, deletedCount={}",
                    methodName, plan.getId(), rule.getSourceType(), deletedCount);
        } catch (DataAccessException e) {
            logExpectedAutoVoucherFailure(methodName, OPERATION_DELETE, plan, rule, e);
        }
    }

    private VoucherDO validateVoucherExists(Long id) {
        VoucherDO voucher = voucherMapper.selectById(id);
        if (voucher == null) {
            throw exception(VOUCHER_NOT_EXISTS);
        }
        return voucher;
    }

    private boolean isValidPlan(PaymentPlanDO plan, String methodName) {
        if (plan == null || plan.getId() == null) {
            log.warn("[{}] 付款计划为空或缺少ID，跳过处理", methodName);
            return false;
        }
        return true;
    }

    private AutoVoucherRule resolveAutoVoucherRule(PaymentPlanDO plan, String methodName) {
        if (PLAN_TYPE_PAYABLE.equals(plan.getType())) {
            return new AutoVoucherRule(SOURCE_TYPE_PAYABLE_PLAN, DIRECTION_INPUT);
        }
        if (PLAN_TYPE_RECEIVABLE.equals(plan.getType())) {
            return new AutoVoucherRule(SOURCE_TYPE_RECEIVABLE_PLAN, DIRECTION_OUTPUT);
        }
        log.warn("[{}] 不支持的付款计划类型，跳过处理，planId={}, type={}", methodName, plan.getId(), plan.getType());
        return null;
    }

    private String resolveCounterparty(PaymentPlanDO plan) {
        if (PLAN_TYPE_PAYABLE.equals(plan.getType())) {
            if (plan.getSupplierId() == null) {
                return null;
            }
            SupplierDO supplier = supplierService.getSupplier(plan.getSupplierId());
            return supplier != null ? supplier.getName() : null;
        }
        if (PLAN_TYPE_RECEIVABLE.equals(plan.getType())) {
            if (plan.getCustomerId() == null) {
                return null;
            }
            CustomerDO customer = customerService.getCustomer(plan.getCustomerId());
            return customer != null ? customer.getName() : null;
        }
        return null;
    }

    private VoucherDO buildAutoVoucher(PaymentPlanDO plan, AutoVoucherRule rule) {
        VoucherDO voucher = new VoucherDO();
        voucher.setOrderId(plan.getOrderId());
        voucher.setVoucherType(null);
        voucher.setDirection(rule.getDirection());
        voucher.setCounterparty(resolveCounterparty(plan));
        voucher.setInvoiceCode(EMPTY_INVOICE_CODE);
        voucher.setAmount(plan.getPlanAmount());
        voucher.setTaxAmount(null);
        voucher.setSourceType(rule.getSourceType());
        voucher.setSourcePlanId(plan.getId());
        voucher.setAutoGenerated(true);
        voucher.setReconcileStatus(RECONCILE_STATUS_PENDING);
        return voucher;
    }

    private void logExpectedAutoVoucherFailure(String methodName, String operation, PaymentPlanDO plan,
                                               AutoVoucherRule rule, DataAccessException e) {
        log.warn("[{}] {} 预制票遇到数据库异常，已记录并跳过，不影响计划主流程，planId={}, sourceType={}, message={}",
                methodName, operation, plan.getId(), rule.getSourceType(), ExceptionUtil.getRootCauseMessage(e), e);
    }

    private boolean isAutoVoucherDuplicateConflict(DataAccessException e) {
        Throwable rootCause = ExceptionUtil.getRootCause(e);
        if (rootCause instanceof SQLIntegrityConstraintViolationException) {
            return containsAutoVoucherUniqueIndex(rootCause.getMessage());
        }
        return containsAutoVoucherUniqueIndex(ExceptionUtil.getRootCauseMessage(e));
    }

    private boolean containsAutoVoucherUniqueIndex(String message) {
        if (message == null) {
            return false;
        }
        String normalizedMessage = message.toLowerCase(Locale.ROOT);
        return normalizedMessage.contains(AUTO_VOUCHER_UNIQUE_INDEX.toLowerCase(Locale.ROOT));
    }

    private boolean hasInvoiceCode(VoucherDO voucher) {
        return voucher.getInvoiceCode() != null && !voucher.getInvoiceCode().trim().isEmpty();
    }

    private static class AutoVoucherRule {
        private final Integer sourceType;
        private final Integer direction;

        private AutoVoucherRule(Integer sourceType, Integer direction) {
            this.sourceType = sourceType;
            this.direction = direction;
        }

        public Integer getSourceType() {
            return sourceType;
        }

        public Integer getDirection() {
            return direction;
        }
    }

}
